site_name: MkDocs Tercen Template
docs_dir: docs/
site_url: https://tercen.com
repo_url: https://github.com/tercen/mkdocs_template
repo_name: tercen/mkdocs_template
edit_uri: edit/main/docs/
site_author: "Tercen Authors"
site_description: "Documentation template for modification."
use_directory_urls: true

copyright: Copyright &copy; 2024 Tercen

theme:
  name: material
  # custom_dir: .docs/overrides/
  font: false
  favicon: https://tercen.com/_assets/brand/fav.png
  logo: ./images/Small Logo white.png
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: custom
  features:
    - content.tabs.link
    - instant
    - navigation.footer
    - navigation.path
    - navigation.sections
    #    - navigation.expand
    #    - navigation.tabs
    #    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - tabs
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - content.action.view
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - git-committers:
      repository: tercen/mkdocs_template
      branch: main
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  #  - exclude:
  #      glob:
  #        - README.md
  #        - "*.gotmpl"
  #        - "*.gotmpl.md"
  #  - awesome-pages
  # - macros:
  #     module_name: .docs/macros/includes/main
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true
      #js_files: []
  # - redirects:
  #     redirect_maps:
  #       README.md: Getting-Started/intro.md
  - mike:
      # these fields are all optional; the defaults are as below...
      version_selector: true # set to false to leave out the version selector
      css_dir: css # the directory to put the version selector's CSS
      javascript_dir: js # the directory to put the version selector's JS
      canonical_version:
        null # the version for <link rel="canonical">; `null`
      # uses the version specified via `mike deploy`
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - tables
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed
extra:
  version:
    provider: mike
# Tercen simplified nav style
nav:
  - Introduction: index.md
#  - User Management: user_management.md
#  - Migrate Operators: migrate_operators.md
#  - Upgrade Server: upgrade_server.md
#  - Update the Main Library: update_library.md

# Example of nested nav style
#nav:
#  - Home: index.md
#  - Getting started:
#      - Guidelines: intro_guidelines.md
#      - Getting started:
#          - Core concepts: getting-started_core-concepts.md
#          - Setting up Tercen Studio:    getting-started_setup-tercen-studio.md
#      - R Operator development:
#          - General workflow: operator-dev_intro.md
#          - "Walkthrough example: R operator": operator-dev_create.md
#          - Deploying an R operator:   operator-dev_deploy.md
#          - Improving an operator:   operator-dev_improve.md
